/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_navclub_dkp4j_platform_tool_FileArchive */

#ifndef _Included_cn_navclub_dkp4j_platform_tool_FileArchive
#define _Included_cn_navclub_dkp4j_platform_tool_FileArchive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_navclub_dkp4j_platform_tool_FileArchive
 * Method:    compress
 * Signature: (Ljava/io/File;Ljava/io/File;)I
 */
JNIEXPORT jint JNICALL Java_cn_navclub_dkp4j_platform_tool_FileArchive_compress
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cn_navclub_dkp4j_platform_tool_FileArchive
 * Method:    decompress
 * Signature: (Ljava/io/File;Ljava/io/File;)I
 */
JNIEXPORT jint JNICALL Java_cn_navclub_dkp4j_platform_tool_FileArchive_decompress
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
