/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_navclub_dkp4j_platform_tool_FileArchive */

#ifndef _Included_cn_navclub_dkp4j_platform_tool_FileArchive
#define _Included_cn_navclub_dkp4j_platform_tool_FileArchive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_navclub_dkp4j_platform_tool_FileArchive
 * Method:    fileEncode
 * Signature: (Ljava/io/File;Ljava/io/File;)I
 */
JNIEXPORT jint JNICALL Java_cn_navclub_dkp4j_platform_tool_FileArchive_fileEncode
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cn_navclub_dkp4j_platform_tool_FileArchive
 * Method:    fileDecode
 * Signature: (Ljava/io/File;Ljava/io/File;)I
 */
JNIEXPORT jint JNICALL Java_cn_navclub_dkp4j_platform_tool_FileArchive_fileDecode
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cn_navclub_dkp4j_platform_tool_FileArchive
 * Method:    byteEncode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_navclub_dkp4j_platform_tool_FileArchive_byteEncode
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_navclub_dkp4j_platform_tool_FileArchive
 * Method:    byteDecode
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_navclub_dkp4j_platform_tool_FileArchive_byteDecode
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
